import Head from 'next/head'
import Link from 'next/link';
import getConfig from 'next/config';
import Movie from "../src/components/movie";
import { useEffect, useState } from 'react';


const { serverRuntimeConfig } = getConfig()
export default function Home(initialData) {
  const [searchMovie, setSearchMovie] = useState([])
  const [searchTerm, setSearchTerm] = useState('');
  const [favorite, setFavorite] = useState([]);


  useEffect(() => {
    setSearchMovie(initialData.allMovies.results)
  }, [initialData])

  const search = async (event) => {
    event.preventDefault()
    let movies = await fetch(`https://api.themoviedb.org/3/search/movie?api_key=${process.env.apiKey}&query=${searchTerm}`)
    movies = await movies.json()
    setSearchMovie(movies.results)
    console.log(movies)
  }

  const AddFavoris = async id => {
    let email = await localStorage.getItem("email");
    let res = fetch('http://localhost:8000/user/favoris' , {
      method: 'POST',
      headers: {
          'Content-Type': 'application/json'
      },
      body: JSON.stringify({id, email}),
    })
      .then(response => response.json())
      .then(data => data)
  };
  return (
    <div className='container'>
      <Head>
        <div className="navbar">
            <title>The clone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="pages/styles.css" />
            <h1>The rotten clone</h1>
    
            <div className='loginLink'>
            <Link href="/login">
            <a style={{ textDecoration: 'none',color: 'black',fontSize: 20}}> Login </a>
            </Link>
            </div>

            <div className='registerLink'>
            <Link href="/register">
              <a style={{ textDecoration: 'none', color: 'black',fontSize: 20 }}> Register </a>
            </Link>
            </div>

            <div className='adminLink'>
            <Link href="/admin">
              <a style={{ textDecoration: 'none', color: 'black',fontSize: 20 }}> Admin </a>
            </Link>
            </div>
        </div>
      </Head>
      
      
      <div className='searchAndBtn'>
        <form onSubmit={search}>
          <input type='text' className='searchBar' placeholder='Look for a movie' value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
        </form>
      </div>

      <div className='movieData'>
        {searchMovie?.map((each, index) => {
          return (
            <div>
            <Movie
              index={each.id}
              title={each.title}
              vote_average={each.vote_average}
              release_date={each.release_date}
              poster_path={each.poster_path}
              overview={each.overview}
            />
            <button onClick={() => AddFavoris(each.id)} className='favBtn'> Add to favourites 📌</button> 
            </div>
          )
        })}
      </div>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps(context) {
  // Fetch data from external API
  let allMovies = await fetch(`https://api.themoviedb.org/3/trending/movie/day?api_key=${serverRuntimeConfig.apiKey}`);
  allMovies = await allMovies.json()
  console.log(allMovies)
  // Pass data to the page via props
  return {
    props: { allMovies: allMovies }
  }
}
